version: '3.8' # Specify the version of Docker Compose

services:
  spring-app:
    build: .
    ports:
      - "8000:8080" # Map host port 8080 to container port 8080
    depends_on:
      - postgres # Ensure the database starts before the app
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/spring-book
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 1912

  postgres:
    image: postgres:15-alpine # Official PostgreSQL image
    environment:
      POSTGRES_DB: spring-book
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1912
    ports:
      - "5432:5432" # Expose PostgreSQL port
    volumes:
      - postgres-data:/var/lib/postgresql/data # Persist PostgreSQL data

volumes:
  postgres-data: # Define a named volume for persistence
