spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/spring-book
    username: postgres
    password: 1912
    driver-class-name: org.postgresql.Driver

    hikari:
      max-lifetime: 1800000 # 30 minutes in milliseconds
      connection-timeout: 30000 # 30 seconds in milliseconds
      idle-timeout: 600000 # 10 minutes in milliseconds

  image:
    dir: src/main/resources/static/

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  liquibase:
    enabled: true
    change-log: classpath:database/db.changelog-master.xml

server:
  port: 8000